[package]
name = "tamagochi-desktop"
version = "1.0.0"
edition = "2021"

[dependencies]
tamagochi-core = { path = "../core", features = ["serialization"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "tamagochi-cli"
path = "src/main.rs"
